name: jupyterlab-collaborative-chat
channels:
  - conda-forge
dependencies:
  - jupyterlab >=4.0.0
  - nodejs >=18,<19
  - python >=3.11,<3.12
  - yarn >=3,<4
  # build
  - hatchling >=1.5.0
  - hatch-jupyter-builder >=0.3.2
  - hatch-nodejs-version
  # Use pip to get the the latest version
  - pip:
    - jupyter_server >=2.0.0
    - jupyter_collaboration
    - jupyter_ydoc >=2.0.0,<3.0.0
    - pycrdt
